
/*
 * ven_acercaDe.java
 *
 * Created on 23/10/2010, 01:28:01 AM
 */

package paq_ventanas;

/**
 *
 * @author Jonathan
 */
public class ven_acercaDe extends javax.swing.JDialog {

    /** Creates new form ven_acercaDe */
    public ven_acercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo5 = new javax.swing.JLabel();
        btn_imagen1 = new javax.swing.JButton();
        lbl_titulo4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_titulo6 = new javax.swing.JLabel();
        lbl_titulo7 = new javax.swing.JLabel();
        lbl_titulo1 = new javax.swing.JLabel();
        lbl_titulo2 = new javax.swing.JLabel();
        lbl_titulo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.orange);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_titulo5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_titulo5.setForeground(new java.awt.Color(255, 153, 153));
        lbl_titulo5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_titulo5.setText("Desarrollado por :");

        btn_imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_imagenes/EscudoUdeGuayaquil.jpg"))); // NOI18N
        btn_imagen1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lbl_titulo4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_titulo4.setForeground(new java.awt.Color(153, 255, 0));
        lbl_titulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo4.setText("Acerca de Melody Neural Network");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText(" Previo a la obtención del título de Ingeniero en Sistemas");

        lbl_titulo6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_titulo6.setForeground(new java.awt.Color(255, 255, 0));
        lbl_titulo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_titulo6.setText("Josué Jonathan Ortega Constantine");

        lbl_titulo7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_titulo7.setForeground(new java.awt.Color(204, 255, 204));
        lbl_titulo7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_titulo7.setText("Guayaquil, Noviembre 2010");

        lbl_titulo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_titulo1.setForeground(new java.awt.Color(255, 204, 51));
        lbl_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo1.setText("Universidad de Guayaquil");

        lbl_titulo2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_titulo2.setForeground(new java.awt.Color(255, 204, 51));
        lbl_titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo2.setText("Facultad de Ciencias Matematicas y Fisicas");

        lbl_titulo3.setForeground(new java.awt.Color(255, 204, 51));
        lbl_titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo3.setText("Carrera de Ingeniería en Sistemas Computacionales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btn_imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_titulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_titulo7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo6, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(lbl_titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_titulo4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo6)
                    .addComponent(lbl_titulo5))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_titulo7)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_titulo1;
    private javax.swing.JLabel lbl_titulo2;
    private javax.swing.JLabel lbl_titulo3;
    private javax.swing.JLabel lbl_titulo4;
    private javax.swing.JLabel lbl_titulo5;
    private javax.swing.JLabel lbl_titulo6;
    private javax.swing.JLabel lbl_titulo7;
    // End of variables declaration//GEN-END:variables

}
