/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ven_TablaBaseDatos.java
 *
 * Created on 23/10/2010, 12:21:14 PM
 */

package paq_ventanas;

/**
 *
 * @author Jonathan
 */
public class ven_TablaBaseDatos extends javax.swing.JInternalFrame {
 private javax.swing.table.DefaultTableCellRenderer tcr = new  javax.swing.table.DefaultTableCellRenderer();
 private int fil;
    /** Creates new form ven_TablaBaseDatos */
    public ven_TablaBaseDatos() {
        initComponents();
    }

    public void llenar_tabla(javax.swing.JTable tabla)
    {
        javax.swing.table.DefaultTableModel modelo= new javax.swing.table.DefaultTableModel();
        
        
         for (int i=0;i< tabla.getColumnCount();i++)
             modelo.addColumn(tabla.getColumnName(i));
      
        this.tbl_tabla.setModel(modelo);
        Object [] filas = new Object[modelo.getColumnCount()];


          for (int i=0;i< tabla.getRowCount();i++)
          { for (int j=0;j<tabla.getColumnCount();j++)
                   filas[j]= tabla.getValueAt(i, j);
                   modelo.addRow(filas);
          }
        formato();
    }
    private void formato()
    {
        tcr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        for(fil=1;fil<this.tbl_tabla.getColumnCount();fil++)
        {
            this.tbl_tabla.getColumnModel().getColumn(fil).setCellRenderer(tcr);
            this.tbl_tabla.getColumnModel().getColumn(fil).setWidth(30);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tabla de Datos de Análisis");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/map_magnify.png"))); // NOI18N
        setOpaque(false);

        tbl_tabla.setBackground(new java.awt.Color(102, 102, 102));
        tbl_tabla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_tabla.setForeground(new java.awt.Color(255, 255, 255));
        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tabla.setEnabled(false);
        tbl_tabla.setGridColor(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(tbl_tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1267, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 40, 1273, 673);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_tabla;
    // End of variables declaration//GEN-END:variables

}
