/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ven_DatosNormalizados.java
 *
 * Created on 19/08/2010, 01:35:25 PM
 */

package paq_ventanas;

/**
 *
 * @author Jonathan
 */
public class ven_DatosNormalizados extends javax.swing.JInternalFrame{

    /** Creates new form ven_DatosNormalizados */

    public ven_DatosNormalizados() {

      
        initComponents();

    }

    public void llenarDatos(String tipo,int fila, int columna)
    {
        if (tipo.equals("IN"))
        {
            this.lbl_tipo.setText("Entrada");
            this.txt_valorReal.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getPatron(fila).getValorEntrada(columna)));
            this.lbl_normal.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getPatron(fila).getValorNormalizadoEntrada(columna)));
            this.lbl_maximo.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getMAXIMO()));            //getMaxEntrada(columna));
            this.lbl_minimo.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getMINIMO()));                            //getMinEntrada(columna)));
        }
        else
        {
            this.lbl_tipo.setText("Salida");
            this.txt_valorReal.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getPatron(fila).getValorSalida(columna)));
            this.lbl_normal.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getPatron(fila).getValorNormalizadoSalida(columna)));
            this.lbl_maximo.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getMAXIMO()));                    //getMaxSalida(columna)));
            this.lbl_minimo.setText(String.valueOf(ven_MDI.nueva_red.getListaPatrones().getMINIMO()));                    //getMinSalida(columna)));
         
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        txt_valorReal = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        lbl_maximo = new javax.swing.JLabel();
        lbl_minimo = new javax.swing.JLabel();
        lbl_normal = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dato Normalizado...");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/pencil.png"))); // NOI18N
        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Maximo Valor :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mínimo Valor :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Valor Real :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor Normalizado :");

        btn_ok.setBackground(java.awt.Color.white);
        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/accept.png"))); // NOI18N
        btn_ok.setText("Aceptar");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        lbl_tipo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(51, 153, 0));
        lbl_tipo.setText("  ");

        lbl_maximo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_maximo.setForeground(new java.awt.Color(51, 153, 0));
        lbl_maximo.setText("   ");

        lbl_minimo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_minimo.setForeground(new java.awt.Color(51, 153, 0));
        lbl_minimo.setText("  ");

        lbl_normal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbl_normal.setForeground(new java.awt.Color(51, 153, 0));
        lbl_normal.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_valorReal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_normal, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addComponent(lbl_minimo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(lbl_maximo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btn_ok)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_maximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_minimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_normal)
                    .addComponent(txt_valorReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_maximo;
    private javax.swing.JLabel lbl_minimo;
    private javax.swing.JLabel lbl_normal;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JTextField txt_valorReal;
    // End of variables declaration//GEN-END:variables

}
