package paq_ventanas;


import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import paq_logica.cls_dibujarGraficas;




/**
 *
 * @author Jonathan
 */
public class ven_curvasAprendizajes extends javax.swing.JInternalFrame implements Runnable {
    
    private ChartPanel panel;
    private cls_dibujarGraficas graficos= new cls_dibujarGraficas();
    public static JFreeChart chart;
    public static Thread hilo;

        public ven_curvasAprendizajes()
        {
            initComponents();
            inicio();
        }

        private void inicio()
        {
            chart=graficos.dibujarCurvaError();
            panel= new ChartPanel(chart);
            javax.swing.GroupLayout Pn_grafico1Layout = new javax.swing.GroupLayout(Pn_grafico1);
            Pn_grafico1.setLayout(Pn_grafico1Layout);
            Pn_grafico1Layout.setHorizontalGroup(
                Pn_grafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pn_grafico1Layout.createSequentialGroup()
                    .addComponent(panel)
                    .addContainerGap( 0, 0))
            );
            Pn_grafico1Layout.setVerticalGroup(
                Pn_grafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Pn_grafico1Layout.createSequentialGroup()
                    .addComponent(panel)
                    .addContainerGap(0 ,0))
            );


        }

        public void iniciar()
            {
                 hilo = new Thread(this);
                 hilo.start();
            }



 public void run() {

            try
            {
                for(;;)
                {
                    this.panel.setChart(graficos.dibujarCurvaError());
                    hilo.sleep(1000);
                    System.out.println(paq_logica.cls_variables_globales.epoca);
                }
            }
            catch (InterruptedException e)
            { System.out.println(e.getMessage()); }
}



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pn_grafico1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Curvas de Aprendizajes");

        Pn_grafico1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Pn_grafico1Layout = new javax.swing.GroupLayout(Pn_grafico1);
        Pn_grafico1.setLayout(Pn_grafico1Layout);
        Pn_grafico1Layout.setHorizontalGroup(
            Pn_grafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        Pn_grafico1Layout.setVerticalGroup(
            Pn_grafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pn_grafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pn_grafico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pn_grafico1;
    // End of variables declaration//GEN-END:variables

}
