/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ven_ConfiguracionGeneral.java
 *
 * Created on 30/06/2010, 11:39:09 PM
 */

package paq_ventanas;
import java.sql.ResultSet;
import java.sql.SQLException;
import paq_logica.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class ven_ConfiguracionGeneral extends javax.swing.JInternalFrame {

    String sql;
    ResultSet resultado;
    cls_sql clase_sql= new cls_sql();
    private JOptionPane mensajes;
    /** Creates new form ven_ConfiguracionGeneral */
    public ven_ConfiguracionGeneral() {
        initComponents();
        this.txt_espaciox.setText( Integer.toString(paq_logica.cls_variables_globales.espacio_x_neuronas));
        this.txt_espacioy.setText( Integer.toString(paq_logica.cls_variables_globales.espacio_y_neuronas));
        this.txt_radiox.setText(Integer.toString(paq_logica.cls_variables_globales.ancho_radio_neurona));
        this.txt_radioy.setText(Integer.toString(paq_logica.cls_variables_globales.alto_radio_neurona));
        this.txt_ciclos.setText(Integer.toString(ven_MDI.nueva_red.getNumCiclos()));
        this.txt_factor.setText(Double.toString(ven_MDI.nueva_red.getFactorAprendizaje()));
        this.txt_error.setText(Double.toString(ven_MDI.nueva_red.getErrorDeseado()));
        this.txt_error1.setText(Double.toString(ven_MDI.nueva_red.getErrorDeseadoPatron()));
        this.txt_momento.setText(Double.toString(ven_MDI.nueva_red.getMomento()));
        this.txt_decimales.setText(Integer.toString(paq_logica.cls_variables_globales.numero_decimales));
        this.txt_muestraHistograma.setText(Integer.toString(paq_logica.cls_variables_globales.tamañoMuestraHistograma));
        this.txt_muestrasNormal.setText(Integer.toString(paq_logica.cls_variables_globales.tamañoMuestraNormal));

        this.cmb_funcion_activacion.setSelectedIndex(ven_MDI.nueva_red.getFuncionActivacion());
        if (paq_logica.cls_variables_globales.aprendizajeEpoca)
             this.chk_ver_aprendizaje_epoca.setSelected(true);
         else
             this.chk_ver_aprendizaje_epoca.setSelected(false);

         if(paq_logica.cls_variables_globales.aprendizajePatron)
             this.chk_ver_aprendizaje_patron.setSelected(true);
         else
             this.chk_ver_aprendizaje_patron.setSelected(false);

        if (paq_logica.cls_variables_globales.curvaNormalHistograma)
                this.chk_ver_curvaNormal.setSelected(true);
        else
                this.chk_ver_curvaNormal.setSelected(false);

        if(paq_logica.cls_variables_globales.curvaError)
                this.chk_ver_curva_error.setSelected(true);
        else
                this.chk_ver_curva_error.setSelected(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        txt_radiox = new javax.swing.JTextField();
        txt_radioy = new javax.swing.JTextField();
        txt_espaciox = new javax.swing.JTextField();
        txt_espacioy = new javax.swing.JTextField();
        chk_ver_aprendizaje_epoca = new javax.swing.JCheckBox();
        chk_ver_aprendizaje_patron = new javax.swing.JCheckBox();
        Pan_control = new javax.swing.JPanel();
        btn_aceptar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_5 = new javax.swing.JLabel();
        txt_factor = new javax.swing.JTextField();
        lbl_8 = new javax.swing.JLabel();
        txt_momento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_7 = new javax.swing.JLabel();
        txt_error = new javax.swing.JTextField();
        lbl_9 = new javax.swing.JLabel();
        txt_error1 = new javax.swing.JTextField();
        lbl_6 = new javax.swing.JLabel();
        txt_ciclos = new javax.swing.JTextField();
        lbl_10 = new javax.swing.JLabel();
        txt_decimales = new javax.swing.JTextField();
        cmb_funcion_activacion = new javax.swing.JComboBox();
        lbl_13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        chk_ver_curva_error = new javax.swing.JCheckBox();
        chk_ver_curvaNormal = new javax.swing.JCheckBox();
        lbl_11 = new javax.swing.JLabel();
        txt_muestrasNormal = new javax.swing.JTextField();
        lbl_12 = new javax.swing.JLabel();
        txt_muestraHistograma = new javax.swing.JTextField();

        jTextField3.setText("jTextField3");

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Configuracion General");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/cog.png"))); // NOI18N
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dibujo RNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 204, 0));

        lbl_1.setBackground(java.awt.Color.white);
        lbl_1.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_1.setText("Radio Y Neurona :");

        lbl_2.setBackground(java.awt.Color.white);
        lbl_2.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_2.setText("Radio X Neurona :");

        lbl_3.setBackground(java.awt.Color.white);
        lbl_3.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_3.setText("Espacio X Neuronas :");

        lbl_4.setBackground(java.awt.Color.white);
        lbl_4.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_4.setText("Espacio Y Neuronas :");

        txt_radiox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_radiox.setForeground(new java.awt.Color(255, 51, 51));
        txt_radiox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_radioy.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_radioy.setForeground(new java.awt.Color(255, 51, 51));
        txt_radioy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_espaciox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_espaciox.setForeground(new java.awt.Color(255, 51, 51));
        txt_espaciox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_espacioy.setFont(new java.awt.Font("Arial", 1, 12));
        txt_espacioy.setForeground(new java.awt.Color(255, 51, 51));
        txt_espacioy.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        chk_ver_aprendizaje_epoca.setBackground(new java.awt.Color(102, 102, 102));
        chk_ver_aprendizaje_epoca.setFont(new java.awt.Font("Tahoma", 1, 11));
        chk_ver_aprendizaje_epoca.setForeground(new java.awt.Color(255, 255, 255));
        chk_ver_aprendizaje_epoca.setSelected(true);
        chk_ver_aprendizaje_epoca.setText("Mostrar Aprendizaje por Epoca");

        chk_ver_aprendizaje_patron.setBackground(new java.awt.Color(102, 102, 102));
        chk_ver_aprendizaje_patron.setFont(new java.awt.Font("Tahoma", 1, 11));
        chk_ver_aprendizaje_patron.setForeground(new java.awt.Color(255, 255, 255));
        chk_ver_aprendizaje_patron.setSelected(true);
        chk_ver_aprendizaje_patron.setText("Mostrar Aprendizaje Patrones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_1)
                    .addComponent(lbl_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_radioy)
                    .addComponent(txt_radiox, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_3)
                    .addComponent(lbl_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_espaciox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_espacioy))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chk_ver_aprendizaje_patron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk_ver_aprendizaje_epoca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_1)
                            .addComponent(txt_radiox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_2)
                            .addComponent(txt_radioy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_espaciox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_espacioy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_3)
                                .addComponent(chk_ver_aprendizaje_epoca))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_4)
                                .addComponent(chk_ver_aprendizaje_patron)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pan_control.setBackground(new java.awt.Color(102, 102, 102));
        Pan_control.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N

        btn_aceptar.setBackground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/accept.png"))); // NOI18N
        btn_aceptar.setMnemonic('A');
        btn_aceptar.setText("Aceptar");
        btn_aceptar.setOpaque(false);
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/page.png"))); // NOI18N
        btn_limpiar.setMnemonic('L');
        btn_limpiar.setText("Limpiar");
        btn_limpiar.setOpaque(false);

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paq_iconos/door_out.png"))); // NOI18N
        btn_salir.setMnemonic('S');
        btn_salir.setText("Salir");
        btn_salir.setOpaque(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pan_controlLayout = new javax.swing.GroupLayout(Pan_control);
        Pan_control.setLayout(Pan_controlLayout);
        Pan_controlLayout.setHorizontalGroup(
            Pan_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_controlLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btn_aceptar)
                .addGap(31, 31, 31)
                .addComponent(btn_limpiar)
                .addGap(18, 18, 18)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        Pan_controlLayout.setVerticalGroup(
            Pan_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pan_controlLayout.createSequentialGroup()
                .addGroup(Pan_controlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros de Red", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 255, 51))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aprendizaje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        lbl_5.setBackground(java.awt.Color.white);
        lbl_5.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_5.setText("Factor Aprendizaje :");

        txt_factor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_factor.setForeground(new java.awt.Color(255, 51, 51));
        txt_factor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbl_8.setBackground(java.awt.Color.white);
        lbl_8.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_8.setForeground(new java.awt.Color(255, 255, 255));
        lbl_8.setText("Momento :");

        txt_momento.setFont(new java.awt.Font("Arial", 1, 12));
        txt_momento.setForeground(new java.awt.Color(255, 51, 51));
        txt_momento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_8)
                    .addComponent(lbl_5))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_momento, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(txt_factor, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_factor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_8)
                    .addComponent(txt_momento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aprendizaje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N

        lbl_7.setBackground(java.awt.Color.white);
        lbl_7.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_7.setText("ErrorTotal Deseado :");

        txt_error.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_error.setForeground(new java.awt.Color(255, 51, 51));
        txt_error.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbl_9.setBackground(java.awt.Color.white);
        lbl_9.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_9.setForeground(new java.awt.Color(255, 255, 255));
        lbl_9.setText("Error por patrón Deseado :");

        txt_error1.setFont(new java.awt.Font("Arial", 1, 12));
        txt_error1.setForeground(new java.awt.Color(255, 51, 51));
        txt_error1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbl_6.setBackground(java.awt.Color.white);
        lbl_6.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_6.setText("Número Ciclos :");

        txt_ciclos.setFont(new java.awt.Font("Arial", 1, 12));
        txt_ciclos.setForeground(new java.awt.Color(255, 51, 51));
        txt_ciclos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbl_10.setBackground(java.awt.Color.white);
        lbl_10.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_10.setForeground(new java.awt.Color(255, 255, 255));
        lbl_10.setText("Decimales  :");

        txt_decimales.setFont(new java.awt.Font("Arial", 1, 12));
        txt_decimales.setForeground(new java.awt.Color(255, 51, 51));
        txt_decimales.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_9)
                    .addComponent(lbl_7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_error1)
                    .addComponent(txt_error, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ciclos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_decimales, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_7)
                    .addComponent(lbl_6)
                    .addComponent(txt_ciclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_9)
                    .addComponent(txt_error1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_decimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_10)))
        );

        cmb_funcion_activacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmb_funcion_activacion.setForeground(new java.awt.Color(255, 51, 51));
        cmb_funcion_activacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_funcion_activacionItemStateChanged(evt);
            }
        });
        cmb_funcion_activacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_funcion_activacionActionPerformed(evt);
            }
        });

        lbl_13.setBackground(java.awt.Color.white);
        lbl_13.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_13.setForeground(new java.awt.Color(255, 255, 255));
        lbl_13.setText("Función Activación :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cmb_funcion_activacion, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_funcion_activacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_13))
                .addGap(55, 55, 55))
        );

        llenar_combo_funcion();

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Propiedades Graficos Estadisticos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 255, 51))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        chk_ver_curva_error.setBackground(new java.awt.Color(102, 102, 102));
        chk_ver_curva_error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chk_ver_curva_error.setForeground(new java.awt.Color(255, 255, 255));
        chk_ver_curva_error.setSelected(true);
        chk_ver_curva_error.setText("Mostrar Curva de Error ");

        chk_ver_curvaNormal.setBackground(new java.awt.Color(102, 102, 102));
        chk_ver_curvaNormal.setFont(new java.awt.Font("Tahoma", 1, 11));
        chk_ver_curvaNormal.setForeground(new java.awt.Color(255, 255, 255));
        chk_ver_curvaNormal.setSelected(true);
        chk_ver_curvaNormal.setText("Mostrar Curva Normal e Histograma");

        lbl_11.setBackground(java.awt.Color.white);
        lbl_11.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_11.setForeground(new java.awt.Color(255, 255, 255));
        lbl_11.setText("Tamaño Muestral Normal :");

        txt_muestrasNormal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_muestrasNormal.setForeground(new java.awt.Color(255, 51, 51));
        txt_muestrasNormal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbl_12.setBackground(java.awt.Color.white);
        lbl_12.setFont(new java.awt.Font("Tahoma", 1, 11));
        lbl_12.setForeground(new java.awt.Color(255, 255, 255));
        lbl_12.setText("Tamaño Muestral histograma :");

        txt_muestraHistograma.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_muestraHistograma.setForeground(new java.awt.Color(255, 51, 51));
        txt_muestraHistograma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_muestrasNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_muestraHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(chk_ver_curva_error, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(178, 178, 178))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(chk_ver_curvaNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(162, 162, 162)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_11)
                            .addComponent(txt_muestrasNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_12)
                            .addComponent(txt_muestraHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(chk_ver_curva_error)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chk_ver_curvaNormal)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                            .addComponent(Pan_control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pan_control, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-709)/2, (screenSize.height-425)/2, 709, 425);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
      try{
         paq_logica.cls_variables_globales.espacio_x_neuronas= Integer.parseInt(this.txt_espaciox.getText());
         paq_logica.cls_variables_globales.espacio_y_neuronas= Integer.parseInt(this.txt_espacioy.getText());
         paq_logica.cls_variables_globales.ancho_radio_neurona= Integer.parseInt(this.txt_radiox.getText());
         paq_logica.cls_variables_globales.alto_radio_neurona= Integer.parseInt(this.txt_radioy.getText());
         paq_logica.cls_variables_globales.numero_decimales= Integer.parseInt(this.txt_decimales.getText());
         paq_logica.cls_variables_globales.tamañoMuestraNormal= Integer.parseInt(this.txt_muestrasNormal.getText());
         paq_logica.cls_variables_globales.tamañoMuestraHistograma=Integer.parseInt(this.txt_muestraHistograma.getText());
         ven_MDI.nueva_red.setFactoraprendizaje(Double.parseDouble(this.txt_factor.getText()));
         ven_MDI.nueva_red.setErrorDeseado(Double.parseDouble(this.txt_error.getText()));
         ven_MDI.nueva_red.setErrorDeseadoPatron(Double.parseDouble(this.txt_error1.getText()));
         ven_MDI.nueva_red.setMomento(Double.parseDouble(this.txt_momento.getText()));
         ven_MDI.nueva_red.setNumeroCiclos(Integer.parseInt(this.txt_ciclos.getText()));
         ven_MDI.nueva_red.setFuncionActivacion(this.cmb_funcion_activacion.getSelectedIndex());


         if (this.chk_ver_aprendizaje_epoca.isSelected())
             paq_logica.cls_variables_globales.aprendizajeEpoca=true;
         else
             paq_logica.cls_variables_globales.aprendizajeEpoca=false;

         if(this.chk_ver_aprendizaje_patron.isSelected())
             paq_logica.cls_variables_globales.aprendizajePatron=true;
         else
             paq_logica.cls_variables_globales.aprendizajePatron=false;

         if (this.chk_ver_curva_error.isSelected())
              paq_logica.cls_variables_globales.curvaError=true;
         else
             paq_logica.cls_variables_globales.curvaError=false;

         if (this.chk_ver_curvaNormal.isSelected())
               paq_logica.cls_variables_globales.curvaNormalHistograma=true;
         else
               paq_logica.cls_variables_globales.curvaNormalHistograma=false;
   
        mensajes.showMessageDialog(null , "Configuracion registrada", "Configuracion", mensajes.INFORMATION_MESSAGE);
        }
      catch(Exception e)
      {
        mensajes.showMessageDialog(null , "Valores no validos!", "Configuracion", mensajes.ERROR_MESSAGE);
      }
}//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
}//GEN-LAST:event_btn_salirActionPerformed

    private void cmb_funcion_activacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_funcion_activacionItemStateChanged
        
    }//GEN-LAST:event_cmb_funcion_activacionItemStateChanged

    private void cmb_funcion_activacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_funcion_activacionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmb_funcion_activacionActionPerformed

    private void llenar_combo_funcion()
    {
    int i;
    int id_funcion[] = new int[4];
    sql= " SELECT fun_descripcion,fun_id FROM redesneuronales.tab_funcion_activacion ";
    resultado=clase_sql.ejecutarSelect(sql);
    try
    {
        i=0;
        while(resultado.next())
        {
            this.cmb_funcion_activacion.addItem(resultado.getString("fun_descripcion"));
             id_funcion[i]=resultado.getInt("fun_id");
            i=i+1;
        }
    }
    catch(SQLException e)
    {e.printStackTrace();}

    }

    private void limpiar()
    {
        this.txt_ciclos.setText("");



    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pan_control;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JCheckBox chk_ver_aprendizaje_epoca;
    private javax.swing.JCheckBox chk_ver_aprendizaje_patron;
    private javax.swing.JCheckBox chk_ver_curvaNormal;
    private javax.swing.JCheckBox chk_ver_curva_error;
    private javax.swing.JComboBox cmb_funcion_activacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_10;
    private javax.swing.JLabel lbl_11;
    private javax.swing.JLabel lbl_12;
    private javax.swing.JLabel lbl_13;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_8;
    private javax.swing.JLabel lbl_9;
    private javax.swing.JTextField txt_ciclos;
    private javax.swing.JTextField txt_decimales;
    private javax.swing.JTextField txt_error;
    private javax.swing.JTextField txt_error1;
    private javax.swing.JTextField txt_espaciox;
    private javax.swing.JTextField txt_espacioy;
    private javax.swing.JTextField txt_factor;
    private javax.swing.JTextField txt_momento;
    private javax.swing.JTextField txt_muestraHistograma;
    private javax.swing.JTextField txt_muestrasNormal;
    private javax.swing.JTextField txt_radiox;
    private javax.swing.JTextField txt_radioy;
    // End of variables declaration//GEN-END:variables

}
